FROM influxdb:1.8.0
RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list && \
sed -i 's|security.debian.org|archive.debian.org/|g' /etc/apt/sources.list && \
sed -i '/stretch-updates/d' /etc/apt/sources.list && \
apt-get update