apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  namespace: jmeter-grafana
  labels:
    releases: {{ .Release.Name }}
data:
  {{- (.Files.Glob "jmeter-scripts/*").AsConfig | nindent 2 }}