apiVersion: v1
kind: Service
metadata:
  name: jmeter-influxdb-svc
  labels:
    database: infuxdb-service
spec:
  selector:
    database: influxdb
  type: ClusterIP
  ports:
    - port: 8086
      name: influx
      targetPort: 8086
    - port: 2003
      name: graphite
      targetPort: 2003
  
  