apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-jmeter
  namespace: jmeter-grafana
  labels:
    database: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      database: influxdb
  template:
    metadata:
      labels:
        database: influxdb
    spec:
      containers:
        - name: influxdb-jmeter-c00
          image: uddeshya307/influxdb:1.8.0
          ports:
          - containerPort: 8086
          env:
          - name: INFLUXDB_DB
            value: my_db
      